
package sk.gov.ekolky.estamp.fo10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import sk.gov.ekolky.estamp.fo10.aponet.RefundReserveRequest;
import sk.gov.ekolky.estamp.fo10.aponet.RefundReserveResponse;
import sk.gov.ekolky.estamp.fo10.aponet.RefundReserveUndoRequest;
import sk.gov.ekolky.estamp.fo10.aponet.RefundReserveUndoResponse;
import sk.gov.ekolky.estamp.fo10.aponet.RegisterApplicationRequest;
import sk.gov.ekolky.estamp.fo10.aponet.RegisterApplicationResponse;
import sk.posta.boc.ispep.PepConfig;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "aponet_PortType", targetNamespace = PepConfig.TARGET_NAMESPACE)
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    sk.gov.ekolky.estamp.fo10.nominal.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.aponet.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.assessment.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.cashdesk.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.infra.ObjectFactory.class,
    sk.gov.ekolky.estamp.xsd10.ObjectFactory.class,
    com.jump_soft.estamp.fo10.common.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.estamp.ObjectFactory.class
})
public interface AponetPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.aponet.RefundReserveResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "refundReserveResponse", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
    public RefundReserveResponse refundReserve(
        @WebParam(name = "refundReserveRequest", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
        RefundReserveRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.aponet.RefundReserveUndoResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "refundReserveUndoResponse", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
    public RefundReserveUndoResponse refundReserveUndo(
        @WebParam(name = "refundReserveUndoRequest", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
        RefundReserveUndoRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.aponet.RegisterApplicationResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "registerApplicationResponse", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
    public RegisterApplicationResponse registerApplication(
        @WebParam(name = "registerApplicationRequest", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
        RegisterApplicationRequest parameters)
        throws BloxFaultMessage
    ;

}
