
package sk.gov.ekolky.estamp.fo10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import sk.gov.ekolky.estamp.fo10.assessment.CancelRequest;
import sk.gov.ekolky.estamp.fo10.assessment.CancelResponse;
import sk.gov.ekolky.estamp.fo10.assessment.CreateRequest;
import sk.gov.ekolky.estamp.fo10.assessment.CreateResponse;
import sk.gov.ekolky.estamp.fo10.assessment.GetRequest;
import sk.gov.ekolky.estamp.fo10.assessment.GetResponse;
import sk.gov.ekolky.estamp.fo10.assessment.ListOperationsRequest;
import sk.gov.ekolky.estamp.fo10.assessment.ListOperationsResponse;
import sk.gov.ekolky.estamp.fo10.assessment.ListRequest;
import sk.gov.ekolky.estamp.fo10.assessment.ListResponse;
import sk.gov.ekolky.estamp.fo10.assessment.OperationConsumeRequest;
import sk.gov.ekolky.estamp.fo10.assessment.OperationConsumeResponse;
import sk.gov.ekolky.estamp.fo10.assessment.OperationDeclareRequest;
import sk.gov.ekolky.estamp.fo10.assessment.OperationDeclareResponse;
import sk.gov.ekolky.estamp.fo10.assessment.OperationExecutionDELTEDRequest;
import sk.gov.ekolky.estamp.fo10.assessment.OperationExecutionDELTEDResponse;
import sk.gov.ekolky.estamp.fo10.assessment.OperationPaymentRequest;
import sk.gov.ekolky.estamp.fo10.assessment.OperationPaymentResponse;
import sk.gov.ekolky.estamp.fo10.assessment.OperationRefundRequest;
import sk.gov.ekolky.estamp.fo10.assessment.OperationRefundResponse;
import sk.gov.ekolky.estamp.fo10.assessment.OperationReserveRequest;
import sk.gov.ekolky.estamp.fo10.assessment.OperationReserveResponse;
import sk.gov.ekolky.estamp.fo10.assessment.OperationTransferRequest;
import sk.gov.ekolky.estamp.fo10.assessment.OperationTransferResponse;
import sk.gov.ekolky.estamp.fo10.assessment.PrintDELETEDRequest;
import sk.gov.ekolky.estamp.fo10.assessment.PrintDELETEDResponse;
import sk.gov.ekolky.estamp.fo10.assessment.UpdateRequest;
import sk.gov.ekolky.estamp.fo10.assessment.UpdateResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "assessment_PortType", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    sk.gov.ekolky.estamp.fo10.nominal.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.infra.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.estamp.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.cashdesk.ObjectFactory.class,
    sk.gov.ekolky.estamp.xsd10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.assessment.ObjectFactory.class
})
public interface AssessmentPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.GetResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "getResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public GetResponse get(
        @WebParam(name = "getRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        GetRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.ListResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public ListResponse list(
        @WebParam(name = "listRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        ListRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.ListOperationsResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listOperationsResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public ListOperationsResponse listOperations(
        @WebParam(name = "listOperationsRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        ListOperationsRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.CreateResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "createResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public CreateResponse create(
        @WebParam(name = "createRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        CreateRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.CancelResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "cancelResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public CancelResponse cancel(
        @WebParam(name = "cancelRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        CancelRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.PrintDELETEDResponse
     * @throws BloxFaultMessage
     */
    @WebMethod(operationName = "print_DELETED")
    @WebResult(name = "print_DELETEDResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public PrintDELETEDResponse printDELETED(
        @WebParam(name = "print_DELETEDRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        PrintDELETEDRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.UpdateResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "updateResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public UpdateResponse update(
        @WebParam(name = "updateRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        UpdateRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.OperationPaymentResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "operationPaymentResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public OperationPaymentResponse operationPayment(
        @WebParam(name = "operationPaymentRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        OperationPaymentRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.OperationDeclareResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "operationDeclareResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public OperationDeclareResponse operationDeclare(
        @WebParam(name = "operationDeclareRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        OperationDeclareRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.OperationReserveResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "operationReserveResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public OperationReserveResponse operationReserve(
        @WebParam(name = "operationReserveRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        OperationReserveRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.OperationExecutionDELTEDResponse
     * @throws BloxFaultMessage
     */
    @WebMethod(operationName = "operationExecution_DELTED")
    @WebResult(name = "operationExecution_DELTEDResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public OperationExecutionDELTEDResponse operationExecutionDELTED(
        @WebParam(name = "operationExecution_DELTEDRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        OperationExecutionDELTEDRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.OperationRefundResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "operationRefundResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public OperationRefundResponse operationRefund(
        @WebParam(name = "operationRefundRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        OperationRefundRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.OperationConsumeResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "operationConsumeResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public OperationConsumeResponse operationConsume(
        @WebParam(name = "operationConsumeRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        OperationConsumeRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.assessment.OperationTransferResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "operationTransferResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
    public OperationTransferResponse operationTransfer(
        @WebParam(name = "operationTransferRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/assessment", partName = "parameters")
        OperationTransferRequest parameters)
        throws BloxFaultMessage
    ;

}
