
package sk.gov.ekolky.estamp.fo10;

import javax.xml.ws.WebFault;

import sk.posta.boc.ispep.PepConfig;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BloxFaultType", targetNamespace = PepConfig.TARGET_NAMESPACE)
public class BloxFaultMessage
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -8577278102194568959L;
	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BloxFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BloxFaultMessage(String message, BloxFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BloxFaultMessage(String message, BloxFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sk.gov.ekolky.estamp.fo10.BloxFaultType
     */
    public BloxFaultType getFaultInfo() {
        return faultInfo;
    }

}
