
package sk.gov.ekolky.estamp.fo10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import sk.gov.ekolky.estamp.fo10.estamp.CreateRequest;
import sk.gov.ekolky.estamp.fo10.estamp.CreateResponse;
import sk.gov.ekolky.estamp.fo10.estamp.ExchangeRequest;
import sk.gov.ekolky.estamp.fo10.estamp.ExchangeResponse;
import sk.gov.ekolky.estamp.fo10.estamp.GetRequest;
import sk.gov.ekolky.estamp.fo10.estamp.GetResponse;
import sk.gov.ekolky.estamp.fo10.estamp.ListOperationsRequest;
import sk.gov.ekolky.estamp.fo10.estamp.ListOperationsResponse;
import sk.gov.ekolky.estamp.fo10.estamp.ListRequest;
import sk.gov.ekolky.estamp.fo10.estamp.ListResponse;
import sk.gov.ekolky.estamp.fo10.estamp.LockRequest;
import sk.gov.ekolky.estamp.fo10.estamp.LockResponse;
import sk.gov.ekolky.estamp.fo10.estamp.OperationConsumeRequest;
import sk.gov.ekolky.estamp.fo10.estamp.OperationConsumeResponse;
import sk.gov.ekolky.estamp.fo10.estamp.UnlockRequest;
import sk.gov.ekolky.estamp.fo10.estamp.UnlockResponse;
import sk.posta.boc.ispep.PepConfig;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "estamp_PortType", targetNamespace = PepConfig.TARGET_NAMESPACE)
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    sk.gov.ekolky.estamp.fo10.infra.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.assessment.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.nominal.ObjectFactory.class,
    sk.gov.ekolky.estamp.xsd10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.cashdesk.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.estamp.ObjectFactory.class
})
public interface EstampPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.GetResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "getResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public GetResponse get(
        @WebParam(name = "getRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        GetRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.ListResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public ListResponse list(
        @WebParam(name = "listRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        ListRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.ListOperationsResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listOperationsResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public ListOperationsResponse listOperations(
        @WebParam(name = "listOperationsRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        ListOperationsRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.CreateResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "createResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public CreateResponse create(
        @WebParam(name = "createRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        CreateRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.ExchangeResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "exchangeResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public ExchangeResponse exchange(
        @WebParam(name = "exchangeRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        ExchangeRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.LockResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "lockResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public LockResponse lock(
        @WebParam(name = "lockRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        LockRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.UnlockResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "unlockResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public UnlockResponse unlock(
        @WebParam(name = "unlockRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        UnlockRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.estamp.OperationConsumeResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "operationConsumeResponse", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
    public OperationConsumeResponse operationConsume(
        @WebParam(name = "operationConsumeRequest", targetNamespace = PepConfig.TARGET_NAMESPACE + "/estamp", partName = "parameters")
        OperationConsumeRequest parameters)
        throws BloxFaultMessage
    ;

}
