
package sk.gov.ekolky.estamp.fo10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import sk.gov.ekolky.estamp.fo10.infra.DeviceStateCheckRequest;
import sk.gov.ekolky.estamp.fo10.infra.DeviceStateCheckResponse;
import sk.gov.ekolky.estamp.fo10.infra.IncidentRegisterRequest;
import sk.gov.ekolky.estamp.fo10.infra.IncidentRegisterResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListCountryRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListCountryResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListDeviceInfoRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListDeviceInfoResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListFeDevicesRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListFeDevicesResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListFeeRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListFeeResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListOfficeRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListOfficeResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListParameterRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListParameterResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListSWPRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListSWPResponse;
import sk.gov.ekolky.estamp.fo10.infra.ListServiceRequest;
import sk.gov.ekolky.estamp.fo10.infra.ListServiceResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "infra_PortType", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    sk.gov.ekolky.estamp.fo10.infra.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.assessment.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.nominal.ObjectFactory.class,
    sk.gov.ekolky.estamp.xsd10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.cashdesk.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.estamp.ObjectFactory.class
})
public interface InfraPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.IncidentRegisterResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "incidentRegisterResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public IncidentRegisterResponse incidentRegister(
        @WebParam(name = "incidentRegisterRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        IncidentRegisterRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.DeviceStateCheckResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "deviceStateCheckResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public DeviceStateCheckResponse deviceStateCheck(
        @WebParam(name = "deviceStateCheckRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        DeviceStateCheckRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListParameterResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listParameterResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListParameterResponse listParameter(
        @WebParam(name = "listParameterRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListParameterRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListServiceResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listServiceResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListServiceResponse listService(
        @WebParam(name = "listServiceRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListServiceRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListFeeResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listFeeResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListFeeResponse listFee(
        @WebParam(name = "listFeeRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListFeeRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListOfficeResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listOfficeResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListOfficeResponse listOffice(
        @WebParam(name = "listOfficeRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListOfficeRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListSWPResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listSWPResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListSWPResponse listSWP(
        @WebParam(name = "listSWPRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListSWPRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListCountryResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listCountryResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListCountryResponse listCountry(
        @WebParam(name = "listCountryRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListCountryRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListDeviceInfoResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listDeviceInfoResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListDeviceInfoResponse listDeviceInfo(
        @WebParam(name = "listDeviceInfoRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListDeviceInfoRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.infra.ListFeDevicesResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "listFeDevicesResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
    public ListFeDevicesResponse listFeDevices(
        @WebParam(name = "listFeDevicesRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/infra", partName = "parameters")
        ListFeDevicesRequest parameters)
        throws BloxFaultMessage
    ;

}
