
package sk.gov.ekolky.estamp.fo10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import sk.gov.ekolky.estamp.fo10.nominal.CheckStateRequest;
import sk.gov.ekolky.estamp.fo10.nominal.CheckStateResponse;
import sk.gov.ekolky.estamp.fo10.nominal.GetReportRequest;
import sk.gov.ekolky.estamp.fo10.nominal.GetReportResponse;
import sk.posta.boc.ispep.PepConfig;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "nominal_PortType", targetNamespace = PepConfig.TARGET_NAMESPACE)
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    sk.gov.ekolky.estamp.fo10.nominal.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.aponet.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.assessment.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.cashdesk.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.infra.ObjectFactory.class,
    sk.gov.ekolky.estamp.xsd10.ObjectFactory.class,
    com.jump_soft.estamp.fo10.common.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.estamp.ObjectFactory.class
})
public interface NominalPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.nominal.CheckStateResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "checkStateResponse", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
    public CheckStateResponse checkState(
        @WebParam(name = "checkStateRequest", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
        CheckStateRequest parameters)
        throws BloxFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.nominal.GetReportResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "getReportResponse", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
    public GetReportResponse getReport(
        @WebParam(name = "getReportRequest", targetNamespace = PepConfig.TARGET_NAMESPACE, partName = "parameters")
        GetReportRequest parameters)
        throws BloxFaultMessage
    ;

}
