
package sk.gov.ekolky.estamp.fo10;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "nominal", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10", wsdlLocation = "http://10.168.10.50:9080/estamp/soa/server/r1_2.wsdl")
public class Nominal
    extends Service
{

    private final static URL NOMINAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sk.gov.ekolky.estamp.fo10.Nominal.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sk.gov.ekolky.estamp.fo10.Nominal.class.getResource(".");
            url = new URL(baseUrl, "http://10.168.10.50:9080/estamp/soa/server/r1_2.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.168.10.50:9080/estamp/soa/server/r1_2.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NOMINAL_WSDL_LOCATION = url;
    }

    public Nominal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Nominal() {
        super(NOMINAL_WSDL_LOCATION, new QName("http://www.ekolky.gov.sk/estamp/fo10", "nominal"));
    }

    /**
     * 
     * @return
     *     returns NominalPortType
     */
    @WebEndpoint(name = "nominal_Port")
    public NominalPortType getNominalPort() {
        return super.getPort(new QName("http://www.ekolky.gov.sk/estamp/fo10", "nominal_Port"), NominalPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NominalPortType
     */
    @WebEndpoint(name = "nominal_Port")
    public NominalPortType getNominalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ekolky.gov.sk/estamp/fo10", "nominal_Port"), NominalPortType.class, features);
    }

}
