
package sk.gov.ekolky.estamp.fo10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import sk.gov.ekolky.estamp.fo10.nominal.CheckStateRequest;
import sk.gov.ekolky.estamp.fo10.nominal.CheckStateResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "nominal_PortType", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    sk.gov.ekolky.estamp.fo10.nominal.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.infra.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.estamp.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.cashdesk.ObjectFactory.class,
    sk.gov.ekolky.estamp.xsd10.ObjectFactory.class,
    sk.gov.ekolky.estamp.fo10.assessment.ObjectFactory.class
})
public interface NominalPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.gov.ekolky.estamp.fo10.nominal.CheckStateResponse
     * @throws BloxFaultMessage
     */
    @WebMethod
    @WebResult(name = "checkStateResponse", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/nominal", partName = "parameters")
    public CheckStateResponse checkState(
        @WebParam(name = "checkStateRequest", targetNamespace = "http://www.ekolky.gov.sk/estamp/fo10/nominal", partName = "parameters")
        CheckStateRequest parameters)
        throws BloxFaultMessage
    ;

}
